# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1pQ9zlWkDPFsqxpD2Rg2VS-a-AgU1UW
"""

import pandas as pd
import numpy as np

# 1. Ingest raw Daft dataset
df = pd.read_csv('daft_housing_data.csv')

# 2. Filter for Dublin properties and clean numeric features
dublin_df = df[df['County'] == 'Dublin'].copy()
dublin_df['Price'] = pd.to_numeric(dublin_df['Price'], errors='coerce')
dublin_df['Floor Area (m2)'] = pd.to_numeric(dublin_df['Floor Area (m2)'], errors='coerce')

# 3. Clean floor areas and calculate Price per Square Meter
valid_area_mask = (dublin_df['Floor Area (m2)'] >= 15) & (dublin_df['Floor Area (m2)'] <= 1000)
dublin_df['Price_Per_SQM'] = np.where(
    valid_area_mask,
    dublin_df['Price'] / dublin_df['Floor Area (m2)'],
    np.nan
)

# 4. Extract Dublin Postal Districts (e.g., Dublin 2, Dublin 4, Dublin 18)
dublin_df['Postal_District'] = dublin_df['Title'].str.extract(r'(Dublin\s?\d{1,2}[A-Za-z]?)', expand=False).fillna('Greater Dublin')

# 5. Segment into Market Tiers for executive reporting
dublin_df['Market_Tier'] = pd.qcut(dublin_df['Price'].dropna(), q=3, labels=['Affordable', 'Mid-Market', 'Premium'])

# 6. Aggregate key metrics by Postal District
district_summary = dublin_df.groupby('Postal_District').agg(
    Listing_Count=('Price', 'count'),
    Avg_Price=('Price', 'mean'),
    Median_Price=('Price', 'median'),
    Avg_Price_Per_SQM=('Price_Per_SQM', 'mean')
).round(2).reset_index()

# 7. Export clean data for Power BI / Tableau visualization
dublin_df.to_csv('cleaned_dublin_housing.csv', index=False)
district_summary.to_csv('dublin_district_summary.csv', index=False)

print("[SUCCESS] Processed 3,000+ Dublin listings from 14,289 total records.")

